name: sismul
description: Apliasi Sismul


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  gradient_app_bar:
  flutter_webview_plugin:
  cloud_firestore: 
  permission_handler: '^4.0.0'
  qrscan: ^0.2.17

 

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  
  uses-material-design: true

  
  assets:
   - assets/images/abhypraya.png
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          
   
  